# The Minecraft version to be fetched. Use "latest" for the newest snapshot.
version = "latest"

# The directory where version-specific files will be stored.
version_folder = "versions"

# The list of languages to be downloaded and processed.
language_list = [
    "en_us",
    "zh_cn",
    "zh_hk",
    "zh_tw",
    "lzh",
    "ja_jp",
    "ko_kr",
    "vi_vn",
]

# Set to true to delete the downloaded client.jar after extracting language files.
remove_client = true

# The directory where output files will be saved.
output_folder = "output"
