# 获取的版本，若为latest则获取最新快照
version = "latest"
# 版本文件夹
version_folder = "versions"
# 语言列表
language_list = ["en_us", "zh_cn", "zh_hk", "zh_tw", "lzh", "ja_jp"]
# 是否删除下载的client.jar
remove_client = true
# 输出文件夹
output_folder = "output"
