# 获取的版本，若为latest则获取最新快照
version = "latest"
# 版本文件夹
version_folder = "versions"
# 语言文件列表
language_list = [
    "zh_CN.lang",
    "zh_TW.lang",
    "zh_cn.lang",
    "zh_tw.lang",
    "zh_cn.json",
    "zh_tw.json",
    "zh_hk.json",
    "lzh.json",
]
# 是否删除下载的client.jar
remove_client = true