[project]
name = "minecraft-translation"
version = "0.1.0"
description = "A project for getting translations of Minecraft: Java Edition."
requires-python = ">=3.13"
dependencies = ["requests>=2.32.4"]
